/*
 * Copyright 2019 Uriah Shaul Mandel
 * Copyright 2025 Damian Kuzmiak
 * Copyright 2026 Zenolabs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id 'com.android.application'
    id 'com.google.devtools.ksp'
}

def keystorePropertiesFile = rootProject.file('app/keystore.properties')
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

def getDate() {
    return new Date().format('MMddHHmm')
}

android {
    namespace = "com.bald.uriah.baldphone"
    compileSdk = 35
    defaultConfig {
        applicationId = "net.zenolabs.zenphone"
        minSdk = 21
        //noinspection OldTargetApi
        targetSdk = 35
        versionCode = 1
        versionName = "1.0.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        manifestPlaceholders = [fullApp: "true", recentCalls: "true"]
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile file('release-key.jks')
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.release
            debuggable false
            minifyEnabled true
            shrinkResources = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            minifyEnabled false
            versionNameSuffix "-debug." + getDate()
        }
    }

    compileOptions {
        targetCompatibility JavaVersion.VERSION_17
        sourceCompatibility JavaVersion.VERSION_17

        coreLibraryDesugaringEnabled = true // java.util.stream for API below 24, java.time for API below 26
    }

    lint {
        abortOnError = false
    }

    sourceSets {
        main {
            assets.srcDir("$buildDir/generated/assets/license")
        }
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.10.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.core:core-ktx:1.16.0' // Newer versions require compileSdk 36+
    implementation 'androidx.core:core-splashscreen:1.2.0'
    implementation 'androidx.lifecycle:lifecycle-process:2.9.4'  // Newer versions require minSdk 23+
    implementation 'androidx.navigation:navigation-fragment-ktx:2.9.8'
    implementation 'androidx.room:room-ktx:2.7.2'  // Newer versions require minSdk 23+
    ksp 'androidx.room:room-compiler:2.7.2'

    implementation 'com.google.android.material:material:1.13.0'
    implementation 'com.googlecode.libphonenumber:libphonenumber:9.0.28'

    implementation 'com.github.bumptech.glide:glide:5.0.5'
    ksp 'com.github.bumptech.glide:ksp:5.0.5'
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'io.coil-kt.coil3:coil-android:3.0.4'  // Newer versions require compileSdk 35+
    implementation 'net.danlew:android.joda:2.10.6'

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'

    // Only for tests
    androidTestImplementation 'androidx.test:rules:1.2.0'
    androidTestImplementation 'com.github.blainepwnz:AndroidContacts:1.14.0'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    testImplementation 'junit:junit:4.13'
}

tasks.register("copyLicenseToAssets", Copy) {
    from(rootProject.file("LICENSE"))
    into("$buildDir/generated/assets/license")
}

preBuild.dependsOn(copyLicenseToAssets)
